### ISSUE TITLE
[small_vector] Deallocations while using reserve/resize

### ISSUE THREAD

**Issue by fabienfl-orc** [slavenf/sfl-library#1]
Hello,

Nice idea, I am surprised there is still no hybrid stack/heap standardized containers like small_vector, fmt::basic_memory_buffer...

I was wondering if reserve/resize should deallocate heap when shrinking. I would expect that only shrink_to_fit would do so.
When being used in a loop, for example, it could cost some useless allocations ?

Thank you

**Comment by slavenf** [comment]
Hello.

Reallocation has not happend if `capacity()` after some operation is same as `capacity()` before that operation, just like in case of `std::vector`.

**Comment by fabienfl-orc** [comment]
My mistake, I have wrongly understood `SFL_DTL::destroy` while browsing and did not enough digging...

Sorry 👍
