### ISSUE TITLE
move constructor failed

### ISSUE THREAD

**Issue by ktprime** [slavenf/sfl-library#3]
```
    cout << "Test constructor(small_vector&&) (N == 0)." << endl;
    {
        sfl::small_vector<xint, 0, TPARAM_ALLOCATOR<xint>> v1({10, 20, 30, 40, 50});

        sfl::small_vector<xint, 0, TPARAM_ALLOCATOR<xint>> v2(std::move(v1));

        // v1 is in a valid but unspecified state

        CHECK(v1.size() == 0); //*************** new add. failed this **********************
        CHECK(v2.size() == 5);
        CHECK(v2.capacity() == 5);
        CHECK(*v2.nth(0) == 10);
        CHECK(*v2.nth(1) == 20);
        CHECK(*v2.nth(2) == 30);
        CHECK(*v2.nth(3) == 40);
        CHECK(*v2.nth(4) == 50);

        sfl::small_vector<xint, 0, TPARAM_ALLOCATOR<xint>> v3(std::move(v2), TPARAM_ALLOCATOR<xint>());

        // v2 is in a valid but unspecified state

        CHECK(v3.size() == 5);
        CHECK(v3.capacity() == 5);
        CHECK(*v3.nth(0) == 10);
        CHECK(*v3.nth(1) == 20);
        CHECK(*v3.nth(2) == 30);
        CHECK(*v3.nth(3) == 40);
        CHECK(*v3.nth(4) == 50);
    }

```

**Comment by slavenf** [comment]
First of all, I need more info. What compiler are you using? How did you run test? Did you alter some file (except that line in your example)?

This should never fail and it does not fail when I test it. I tested it with GCC and Clang, new and old versions, including GCC 4.8.

**Comment by ktprime** [comment]
I test  in vs-2022, gcc-12, llvm-17 version.
the origin cases is OK, but I have just changed above case

`sfl::small_vector<xint, 0, TPARAM_ALLOCATOR<xint>> v2(std::move(v1));`
the v1 must be empty after moved.

![image](https://github.com/slavenf/sfl-library/assets/1461362/0fc48d18-236c-41b4-887b-296a7305bc1e)

other size is not empty.

**Comment by slavenf** [comment]
You listed me three different compilers, but which compiler is used when you get error?

Please show me the exact command that you typed in command line to compile.

**Comment by slavenf** [comment]
One more thing. If `v1.size()` is not zero then what is it?

Could you add the following after `v2(std::move(v1));`
```
cout << "v1.size(): " << v1.size() << endl;
for (int i = 0; i < v1.size(); ++i)
{
    cout << "v1[" << i << "]: " << v1[i] << endl;
}
```
Please show me the output.

**Comment by ktprime** [comment]
vs2022
![image](https://github.com/slavenf/sfl-library/assets/1461362/572c5169-173c-468c-95f9-7e583d0ce724)

**Comment by ktprime** [comment]
![image](https://github.com/slavenf/sfl-library/assets/1461362/d8e299fe-aa91-4666-9d79-f7cdcf1f10bf)

**Comment by ktprime** [comment]
![image](https://github.com/slavenf/sfl-library/assets/1461362/2ddcd819-0f04-40d2-aff9-7797206b9103)

**Comment by ktprime** [comment]
if  `sfl::small_vector<int, 2> v3 = { 1,2, 3};`
the above test code is OK

**Comment by slavenf** [comment]
> ![image](https://private-user-images.githubusercontent.com/1461362/290790607-2ddcd819-0f04-40d2-aff9-7797206b9103.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MzQ5NTAsIm5iZiI6MTcwMjYzNDY1MCwicGF0aCI6Ii8xNDYxMzYyLzI5MDc5MDYwNy0yZGRjZDgxOS0wZjA0LTQwZDItYWZmOS03Nzk3MjA2YjkxMDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTVUMTAwNDEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTk1ZjAzMjk2ZmU1Njg3NjQ5N2ZiZmZjOWY3ZGExMWRkOWQ2NWMyY2Y5YmU5N2NiNWY0MjUyMDVkMGFhNzUxOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rppgcqDHgHZZEKnNWs6p7LGju1GPh1d6q_t5P9GEPxU)

No problems here. Everything is ok. `v3.size` must be 2 and it is as you can see.

**Comment by slavenf** [comment]
> if `sfl::small_vector<int, 2> v3 = { 1,2, 3};` the above test code is OK. the bug code in line 2097 ![image](https://private-user-images.githubusercontent.com/1461362/290791363-b0c9427a-d31e-4df0-9400-0a1a4e5e3057.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MzUyMjMsIm5iZiI6MTcwMjYzNDkyMywicGF0aCI6Ii8xNDYxMzYyLzI5MDc5MTM2My1iMGM5NDI3YS1kMzFlLTRkZjAtOTQwMC0wYTFhNGU1ZTMwNTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTVUMTAwODQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjBhOGEyNGQyMGE1OTg1NThiZDhiMGM0OGI4NzYyMWIyMzNmODNjZGYxZWE2ZTk5NDc3NmViZmY2ODdmYjhjYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tc1h2org512G1i3DiK7-AUVftSLiAYINieWqad0cwPA)

No problems here. There is no bugs here.

**Comment by ktprime** [comment]
std::move(v) means v will be empty after be called.
I do not know if it's a feature of your lib.

using QuicFrames = absl::InlinedVector<QuicFrame, 2>;
//using QuicFrames = sfl::small_vector<QuicFrame, 2>; //crashed in my programming.

**Comment by slavenf** [comment]
It is not feature of my library. 

You probably misunderstand something. You probably even do not have bug in your code.
As it is documentation says:

- `other` is not guaranteed to be empty after the move.

- `other` is in a valid but unspecified state after the move.

One more time. Other is not guaranteed **to be empty** after move. It is in valid but unspecified state after the move. That doesn't mean it is empty.

Check the following example (there are no errors in this example):
```
#include "sfl/small_vector.hpp"

int main()
{
	{
		sfl::small_vector<int, 2> v1 = {1, 2};
		
		auto v2(std::move(v1)); // element-wise move from v1 to v2
		
		assert(v1.size() == 2);
		assert(v1[0] == 1);
		assert(v1[1] == 2);
		
		assert(v2.size() == 2);
		assert(v2[0] == 1);
		assert(v2[1] == 2);
	}
	
	{
		sfl::small_vector<int, 2> v1 = {1, 2, 3};
		
		auto v2(std::move(v1)); // trasfer pointer ownership from v1 to v2
		
		assert(v1.size() == 0);
		
		assert(v2.size() == 3);
		assert(v2[0] == 1);
		assert(v2[1] == 2);
		assert(v2[2] == 3);
	}
	
	{
		sfl::small_vector<int, 0> v1 = {1, 2, 3};
		
		auto v2(std::move(v1)); // trasfer pointer ownership from v1 to v2
		
		assert(v1.size() == 0);
		
		assert(v2.size() == 3);
		assert(v2[0] == 1);
		assert(v2[1] == 2);
		assert(v2[2] == 3);
	}
}

```

**Comment by slavenf** [comment]
After you do `auto v2(std::move(v1))` you **MUST** check what is `v1.size()`.

In the first example above:
```
	{
		sfl::small_vector<int, 2> v1 = {1, 2};
		
		auto v2(std::move(v1)); // element-wise move from v1 to v2
		
		assert(v1.size() == 2);
		assert(v1[0] == 1);
		assert(v1[1] == 2);
		
		assert(v2.size() == 2);
		assert(v2[0] == 1);
		assert(v2[1] == 2);
	}
```
it is true that `v1.size() == 2` but it is just lucky. Do not expect that `v1.size()` is zero or some other number after move. I know how my containers works under-the-hood and I know that in the first example `v1.size()` is `2` and what is the value of elements. **Generally, you should not assume `v1.size()` after `auto v2(std::move(v1));` but you must check what is before you continue using the container.**

**Comment by ktprime** [comment]
I have test the following small_vector lib. maybe yours is some different with move action.

```
        benchv<std::vector<long>, AN>("std::vector", en);
        benchv<sv::small_vector<long, AE>, AN>("sv::vector", en);
        benchv<rocksdb::autovector<long, AE>, AN>("rdb::autovector", en);
        benchv<llvm_vecsmall::SmallVector<long, AE>, AN>("llvm::vector", en);
        benchv<absl::InlinedVector<long, AE>, AN>("absl::InlinedVector", en);
        benchv<sfl::small_vector<long, AE>, AN>("sfl::vector", en);
```

**Comment by slavenf** [comment]
I wouldn't call it _feature_. Maybe _property_ is a better word to describe such behavior.

Nevertheless, do not make assumptions and always check documentation whenever you are using move semantics and containers. This is general advice.

I am still a little bit confused because your first message where you claimed that `CHECK(v1.size() == 0);` fails but it doesn't fail in that particular case. I assume you mixed test cases. The same check would fail in case before where I'm testing small vector when `N > 0`. Your message contains case where I'm testing small vector when `N == 0`.

**Comment by slavenf** [comment]
I am closing this since there are no problems or bugs.

If you have more questions, just ask.
