### ISSUE TITLE
segmented_vector and push_front specialization.

### ISSUE THREAD

**Issue by ZehMatt** [slavenf/sfl-library#7]
Are there any plans to add this specialized function to match the deque interface? One of the reasons to why deque is pretty good is that push_front is reasonably fast. I'm not exactly sure how its implemented for deque but if I had to guess they just allocate a new block when the one at the beginning is full and only move the last element into the new block rather than shifting all elements across all the blocks.

**Comment by slavenf** [comment]
When I started writing this library, I just needed something like `std::vector`, but with "segmented" storage. I haven't had in the plan to match deque's interface.

Since you asked for that, I think it is a good time to put this to at the top of my todo list. 

I know how to do it, but I will need some time. I don't know, maybe 2, maybe 3 months.

So, I will implement:
- `emplace_front`
- `push_front`
- `pop_front`

Did I miss something?

**Comment by ZehMatt** [comment]
Seems about right, I highly appreciate your work on this so big thanks.

**Comment by slavenf** [comment]
Hey @ZehMatt.

I have progressed faster than I expected. Please check branch [`develop`](https://github.com/slavenf/sfl-library/tree/develop).

I created new container `sfl::segmented_devector` (segmented double-ended vector) that allows fast insertion and deletion at both its beginning and its end.

I didn't want to change `sfl::segmented_vector`. I don't want to go into details, but due to internal organization, `segmented_vector` has much faster `operator[]`, `at()` and `nth()` than `segmented_devector`.

When looking at assembly produced by GCC with `-O3` flag, `segmented_vector::operator[]` is translated into 5 assembly instructions and `segmented_devector::operator[]` is translated into 20-25 assembly instructions!!! The similar result is for `at()` and `nth()`. Maybe it looks like insignificant difference, but that is actually a huge difference, especially in case if you are accessing unsequentially to elements of vector huge number of times. That is the main reason why I have created `segmented_vector` just like that, i.e. to have as fastest as possible `operator[]`, `at()` and `nth()`. Not going into specifics of my problems, in the past, I often had huuuge vectors (100 millions elements or more) and I often used these member functions. I always filled such vectors using `push_back` and I never inserted into the middle so I didn't worry about shifting of elements inside container.

So, segmented double-ended vector is completed, but I am not going to merge to master branch right now. I would like to take some time to go through everything once again, maybe I find some place for minor performance improvements. I also would like to review documentation once again.

I would also like to hear your comments if you are willing to test it from develop branch.

**Comment by ZehMatt** [comment]
> Hey @ZehMatt.
> 
> I have progressed faster than I expected. Please check branch [`develop`](https://github.com/slavenf/sfl-library/tree/develop).
> 
> I created new container `sfl::segmented_devector` (segmented double-ended vector) that allows fast insertion and deletion at both its beginning and its end.
> 
> I didn't want to change `sfl::segmented_vector`. I don't want to go into details, but due to internal organization, `segmented_vector` has much faster `operator[]`, `at()` and `nth()` than `segmented_devector`.
> 
> When looking at assembly produced by GCC with `-O3` flag, `segmented_vector::operator[]` is translated into 5 assembly instructions and `segmented_devector::operator[]` is translated into 20-25 assembly instructions!!! The similar result is for `at()` and `nth()`. Maybe it looks like insignificant difference, but that is actually a huge difference, especially in case if you are accessing unsequentially to elements of vector huge number of times. That is the main reason why I have created `segmented_vector` just like that, i.e. to have as fastest as possible `operator[]`, `at()` and `nth()`. Not going into specifics of my problems, in the past, I often had huuuge vectors (100 millions elements or more) and I often used these member functions. I always filled such vectors using `push_back` and I never inserted into the middle so I didn't worry about shifting of elements inside container.
> 
> So, segmented double-ended vector is completed, but I am not going to merge to master branch right now. I would like to take some time to go through everything once again, maybe I find some place for minor performance improvements. I also would like to review documentation once again.
> 
> I would also like to hear your comments if you are willing to test it from develop branch.

That is amazing news, I will do some testing with it.

**Comment by ZehMatt** [comment]
So I did some benchmarking, the results are pretty good, here is what I've got with compiling it using MSVC x64:
```
CPU: Intel i7-8700K @ 3.70 GHz
---------------------------------------------------------------------------------------------------------------------
Benchmark                                                           Time             CPU   Iterations UserCounters...
---------------------------------------------------------------------------------------------------------------------
BM_push_back<std::deque<TestStruct>>                            19637 us        19848 us           37 Elements=7.4M
BM_push_front<std::deque<TestStruct>>                           18213 us        18159 us           37 Elements=7.4M
BM_erase_random<std::deque<TestStruct>>                      10527433 us     10531250 us            1 Elements=200k
BM_iterate<std::deque<TestStruct>>                                685 us          698 us         1120 Elements=1.12k

BM_push_back<sfl::segmented_devector<TestStruct, 4096>>           373 us          372 us         1848 Elements=369.6M
BM_push_front<sfl::segmented_devector<TestStruct, 4096>>          380 us          377 us         1867 Elements=373.4M
BM_erase_random<sfl::segmented_devector<TestStruct, 4096>>    5655684 us      5656250 us            1 Elements=200k
BM_iterate<sfl::segmented_devector<TestStruct, 4096>>             291 us          292 us         2358 Elements=2.358k

BM_push_back<sfl::segmented_vector<TestStruct, 4096>>             401 us          396 us         1659 Elements=331.8M
BM_push_front<sfl::segmented_vector<TestStruct, 4096>>       23425498 us     23421875 us            1 Elements=200k
BM_erase_random<sfl::segmented_vector<TestStruct, 4096>>     12151571 us     12140625 us            1 Elements=200k
BM_iterate<sfl::segmented_vector<TestStruct, 4096>>               347 us          345 us         2036 Elements=2.036k

BM_push_back<std::vector<TestStruct>>                            3802 us         3753 us          179 Elements=35.8M
BM_push_front<std::vector<TestStruct>>                       16789623 us     16796875 us            1 Elements=200k
BM_erase_random<std::vector<TestStruct>>                     19544553 us     19531250 us            1 Elements=200k
BM_iterate<std::vector<TestStruct>>                               276 us          276 us         2489 Elements=2.489k
```
The code can be found here: https://github.com/ZehMatt/sfl-benchmarks, should be fairly simple to compile as it uses CMake, might be useful to you in case you want to test more compilers and systems.

The only thing that seems to stick out a bit is `BM_push_front<sfl::segmented_vector<TestStruct, 4096>>`, not sure how vector is faster at that, push_front is in this case just `insert(x.begin(), ...)`

**Comment by slavenf** [comment]
Thank you for benchmarks. 

I am not suprised that inserting to the front of segmented vector is slower than standard vector. Actually, I expected it would be slower.

Explanation is simple. Iterators in standard vector are actually pointers, and iterators in segmented vector are more complex. If you look into the implementation of `segmented_vector::emplace`, you will see there is a call to `std::move_backward` that moves all elements one place to the end to make place at the front for new element. Identical implementation is in standard vector. Arguments to `std::move_backward` are iterators. Decrementing (and incrementing) `segmented_vector::iterator` is more expensive than decrementing raw pointer as it is in case of standard vector.

**Comment by slavenf** [comment]
I've made quick analysis thanks to your benchmarks. Now I see that segmented vector and devector can be significantly improved at several places. I will do more benchmarks and improvements in the following days. Stay tuned...

**Comment by slavenf** [comment]
Added small improvements into `develop` branch.

Added benchmarks into `develop` branch. 

`emplace_back` and `emplace_front` are faster than `std::deque`.

Random emplacing and erasing is slower than `std::deque` but I know how to fix that and I expect it would be the same or better than `std::deque`.

Notice that `segmented_vector` is much faster in random access than `segmented_devector` and `std::deque`.

Used benchmarking library: https://github.com/martinus/nanobench

### emplace_back

|     ns/emplace_back |      emplace_back/s |    err% |     total | emplace_back
|--------------------:|--------------------:|--------:|----------:|:-------------
|                2.69 |      371,812,327.43 |    0.2% |      2.69 | `std::deque<int>`
|                2.59 |      385,744,294.97 |    0.2% |      2.60 | `sfl::segmented_devector<int, 1024>`
|                2.41 |      415,284,737.49 |    0.2% |      2.41 | `sfl::segmented_vector<int, 1024>`
|                1.59 |      627,939,108.24 |    0.2% |      1.59 | `std::vector<int>`

### emplace_front

|    ns/emplace_front |     emplace_front/s |    err% |     total | emplace_front
|--------------------:|--------------------:|--------:|----------:|:--------------
|                1.41 |      709,159,403.57 |    3.9% |      1.42 | `std::deque<int>`
|                0.98 |    1,019,327,831.78 |    1.4% |      0.99 | `sfl::segmented_devector<int, 1024>`

### emplace random

|          ns/emplace |           emplace/s |    err% |     total | emplace random
|--------------------:|--------------------:|--------:|----------:|:---------------
|              139.82 |        7,152,124.25 |    0.6% |      0.14 | `std::deque<int>`
|              850.58 |        1,175,670.58 |    0.5% |      0.85 | `sfl::segmented_devector<int, 1024>`
|            1,817.32 |          550,260.32 |    0.4% |      1.82 | `sfl::segmented_vector<int, 1024>`
|               84.14 |       11,884,642.90 |    0.6% |      0.09 | `std::vector<int>`

### erase random

|            ns/erase |             erase/s |    err% |     total | erase random
|--------------------:|--------------------:|--------:|----------:|:-------------
|            1,934.78 |          516,854.55 |    0.2% |      4.84 | `std::deque<int>`
|           13,760.26 |           72,673.06 |    0.3% |     34.47 | `sfl::segmented_devector<int, 1024>`
|           24,877.11 |           40,197.60 |    0.5% |     62.34 | `sfl::segmented_vector<int, 1024>`
|            2,536.45 |          394,252.58 |    0.1% |      6.34 | `std::vector<int>`

### operator[]

|       ns/operator[] |        operator[]/s |    err% |     total | operator[]
|--------------------:|--------------------:|--------:|----------:|:-----------
|               11.74 |       85,168,736.28 |    0.2% |     11.75 | `std::deque<int>`
|               13.44 |       74,418,174.34 |    0.2% |     13.48 | `sfl::segmented_devector<int, 1024>`
|                8.75 |      114,289,402.24 |    0.4% |      8.78 | `sfl::segmented_vector<int, 1024>`
|                6.32 |      158,153,014.45 |    0.3% |      6.35 | `std::vector<int>`

### at()

|             ns/at() |              at()/s |    err% |     total | at()
|--------------------:|--------------------:|--------:|----------:|:-----
|               13.31 |       75,138,436.75 |    1.4% |     13.42 | `std::deque<int>`
|               13.58 |       73,634,949.06 |    0.7% |     13.66 | `sfl::segmented_devector<int, 1024>`
|                9.06 |      110,391,857.87 |    0.3% |      9.07 | `sfl::segmented_vector<int, 1024>`
|                6.75 |      148,144,473.07 |    0.3% |      6.77 | `std::vector<int>`

### nth()

|            ns/nth() |             nth()/s |    err% |     total | nth()
|--------------------:|--------------------:|--------:|----------:|:------
|               12.19 |       82,009,245.21 |    0.3% |     12.21 | `sfl::segmented_devector<int, 1024>`
|                7.93 |      126,120,850.98 |    0.5% |      7.95 | `sfl::segmented_vector<int, 1024>`

### iterate all

|        ns/iteration |         iteration/s |    err% |     total | iterate all
|--------------------:|--------------------:|--------:|----------:|:------------
|                0.55 |    1,826,945,860.17 |    0.1% |      2.74 | `std::deque<int>`
|                0.51 |    1,954,814,788.48 |    0.2% |      2.56 | `sfl::segmented_devector<int, 1024>`
|                0.51 |    1,951,327,948.92 |    0.2% |      2.56 | `sfl::segmented_vector<int, 1024>`
|                0.15 |    6,802,228,273.94 |    0.1% |      0.74 | `std::vector<int>`

**Comment by ZehMatt** [comment]
Thanks for the update, I'll run the benchmarks that I made against the updated code, the MSVC deque implementation is notoriously bad so I expect it to be already better in most situations which it already was.

**Comment by slavenf** [comment]
I have never used MSVC deque, but yes, according to benchmarks, it is utterly slow.

I have made additional improvements into `develop` branch. Please see it now. Both segmented vector and devector are now significantly faster. Segmented devector is fast as GCC deque and sometimes it is even faster. Results are below.

I don't know about you, but I have hard time to make benchmark results consistent. For example, results for `emplace_back` varies ±0.05ns between runs. I have disabled CPU frequency scaling and set CPU governor to "performance", but still variations between runs. Maybe I am wrongly using that benchmarking library. If you check my benchmarking code, you will see I set few warmup iterations that don't go into the statistics.

Nevertheless, my conclusion is that `segmented_devector` is better than GCC deque. `segmented_vector` has faster random access than `segmented_devector`.


|    ns/emplace_front |     emplace_front/s |    err% |     total | emplace_front (100000000 elements)
|--------------------:|--------------------:|--------:|----------:|:-----------------------------------
|                2.90 |      345,146,235.33 |    0.4% |      2.90 | `std::deque<int>`
|                3.07 |      326,250,627.95 |    0.0% |      3.07 | `sfl::segmented_devector<int, 1024>`
|                2.67 |      374,800,455.53 |    0.0% |      2.67 | `sfl::segmented_devector<int, 262144>`

|     ns/emplace_back |      emplace_back/s |    err% |     total | emplace_back (100000000 elements)
|--------------------:|--------------------:|--------:|----------:|:----------------------------------
|                4.56 |      219,517,638.09 |    0.1% |      4.56 | `std::deque<int>`
|                4.58 |      218,377,674.77 |    0.1% |      4.58 | `sfl::segmented_devector<int, 1024>`
|                4.49 |      222,643,622.03 |    0.0% |      4.49 | `sfl::segmented_devector<int, 262144>`
|                4.58 |      218,505,862.38 |    0.1% |      4.58 | `sfl::segmented_vector<int, 1024>`
|                4.48 |      223,180,549.33 |    0.0% |      4.48 | `sfl::segmented_vector<int, 262144>`
|                3.49 |      286,915,409.53 |    0.1% |      3.49 | `std::vector<int>`

|          ns/emplace |           emplace/s |    err% |     total | emplace @ begin() (100000000 elements)
|--------------------:|--------------------:|--------:|----------:|:---------------------------------------
|                3.09 |      323,237,622.50 |    0.2% |      3.09 | `std::deque<int>`
|                3.12 |      320,249,512.29 |    0.3% |      3.12 | `sfl::segmented_devector<int, 1024>`
|                2.69 |      371,084,081.19 |    0.0% |      2.70 | `sfl::segmented_devector<int, 262144>`

|          ns/emplace |           emplace/s |    err% |     total | emplace @ end() (100000000 elements)
|--------------------:|--------------------:|--------:|----------:|:-------------------------------------
|                4.63 |      215,779,199.19 |    0.1% |      4.63 | `std::deque<int>`
|                4.60 |      217,275,536.16 |    0.0% |      4.60 | `sfl::segmented_devector<int, 1024>`
|                4.49 |      222,569,138.51 |    0.0% |      4.49 | `sfl::segmented_devector<int, 262144>`
|                4.65 |      214,885,534.64 |    0.0% |      4.65 | `sfl::segmented_vector<int, 1024>`
|                4.56 |      219,139,569.58 |    0.1% |      4.56 | `sfl::segmented_vector<int, 262144>`
|                3.48 |      287,395,448.09 |    0.1% |      3.48 | `std::vector<int>`

|          ns/emplace |           emplace/s |    err% |     total | emplace @ random position (100000 elements)
|--------------------:|--------------------:|--------:|----------:|:--------------------------------------------
|            2,298.96 |          434,978.82 |    0.4% |      2.30 | `std::deque<int>`
|              754.51 |        1,325,355.56 |    0.2% |      0.75 | `sfl::segmented_devector<int, 1024>`
|              637.04 |        1,569,762.42 |    0.2% |      0.64 | `sfl::segmented_devector<int, 262144>`
|            1,465.57 |          682,329.31 |    0.1% |      1.46 | `sfl::segmented_vector<int, 1024>`
|            1,266.15 |          789,797.57 |    0.1% |      1.27 | `sfl::segmented_vector<int, 262144>`
|            1,260.24 |          793,501.08 |    0.2% |      1.26 | `std::vector<int>`

|       ns/operator[] |        operator[]/s |    err% |     total | operator[] (10000000 elements)
|--------------------:|--------------------:|--------:|----------:|:-------------------------------
|               12.56 |       79,607,036.42 |    1.0% |      1.27 | `std::deque<int>`
|               11.18 |       89,455,682.08 |    0.5% |      1.12 | `sfl::segmented_devector<int, 1024>`
|                8.33 |      120,019,409.06 |    1.9% |      0.84 | `sfl::segmented_vector<int, 1024>`
|                5.79 |      172,857,670.74 |    0.3% |      0.58 | `std::vector<int>`

|             ns/at() |              at()/s |    err% |     total | at() (10000000 elements)
|--------------------:|--------------------:|--------:|----------:|:-------------------------
|               13.22 |       75,656,033.90 |    0.5% |      1.33 | `std::deque<int>`
|               12.07 |       82,825,600.32 |    0.0% |      1.21 | `sfl::segmented_devector<int, 1024>`
|                9.55 |      104,716,239.85 |    0.5% |      0.95 | `sfl::segmented_vector<int, 1024>`
|                6.32 |      158,269,011.82 |    0.3% |      0.63 | `std::vector<int>`

|            ns/nth() |             nth()/s |    err% |     total | nth() (10000000 elements)
|--------------------:|--------------------:|--------:|----------:|:--------------------------
|               11.21 |       89,225,499.42 |    0.4% |      1.12 | `sfl::segmented_devector<int, 1024>`
|                8.20 |      121,930,463.08 |    0.4% |      0.83 | `sfl::segmented_vector<int, 1024>`

|        ns/iteration |         iteration/s |    err% |     total | iterate all (100000000 elements)
|--------------------:|--------------------:|--------:|----------:|:---------------------------------
|                0.46 |    2,161,971,324.37 |    0.6% |      0.46 | `std::deque<int>`
|                0.54 |    1,863,143,797.11 |    0.2% |      0.54 | `sfl::segmented_devector<int, 1024>`
|                0.44 |    2,272,958,262.11 |    0.6% |      0.44 | `sfl::segmented_vector<int, 1024>`
|                0.17 |    5,964,469,120.65 |    0.6% |      0.17 | `std::vector<int>`

**Comment by ZehMatt** [comment]
I think benchmarking code is one of the hardest things to do these days, there are so many factors where you have no control over so there will be a certain degree of variation but its typically a small margin. The results are looking pretty good, the iteration time of vector vs segmented_vector look a bit off to me, can you re-run that with a block size of 4096? If you look at my data the gap isn't as nearly as big as yours, so that's why I'm thinking a bigger block size will improve that.

**Comment by ZehMatt** [comment]
That's interesting, I made sure to run it multiple times and the delta between vector and segmented_vector was pretty stable within of 4-5 us at most, Google Benchmark uses multiple iterations until it becomes somewhat stable, so I'm not sure its because of that, I also checked the commit history and yeah nothing seems to have changed on the iterators, at least not directly. But then I also think that its pretty solid as is even with the strange discrepancy between the commits. I'm overall pretty happy with the results and quite thankful for your effort in providing a deque like container, I looked for alternatives before but haven't been too happy so this is a very nice alternative.

**Comment by slavenf** [comment]
I'm glad that you like it. Thank you for the nice words. 

Segmented double-vector is finished. I have fully implemented hierarchical algorithms that are aware of segmented iterators. Now both segmented vector and segmented devector are using them and the execution time of all member functions should be shorter.

I still have no idea how to make the best benchmark. When I started working on segmented vector three years ago I tested it in real code. It was a computer program that processed gigabytes and gigabytes of real data and it was the best benchmark ever.

I must finish writing documentation and then I will merge it into the master branch and increment version. Probably this weekend, maybe next. Until then, you can use develop branch.
If you have some suggestions or comments, please tell me.

**Comment by ZehMatt** [comment]
Sounds great, and thanks again. I will probably add this library as a dependency quite soon in OpenLoco and potentially OpenRCT2, its definitely well suited for game development. I think one container to to complement it all would be fixed_vector, close to what small_vector does except it can never grow beyond specified N, I can perhaps look into contributing that if you think this is a suitable container for this library.

**Comment by ZehMatt** [comment]
> Great.
> 
> You wouldn't believe me, but I already have fixed_vector ready, but I have never uploaded it to the GitHub. Actually, I call it static_vector. I also have static_flat_set. I had a plan to make static versions of all containers, but I put that idea aside. I am not sure if such containers would be used by anyone. Also there is [Embedded Template Library](https://www.etlcpp.com/) that already has static versions of these containers. Ok, that library is primaryly made for embedded systems, but everything can be used on desktop systems. What do you think?

If you already have static_vector and static_flat_set I think it would be a good addition, for game development we definitely try to avoid as many allocations as possible, here is an example of one https://github.com/OpenRCT2/OpenRCT2/blob/dec5140f20d57cf3a534ff4ee7685c1f78298aee/src/openrct2/ride/RideConstruction.cpp#L1464 , there are probably way more scenarios where this is useful, I mean people will probably just use a vector for such things but when the maximum is known and its not a large amount of elements then a fixed/static vector is always handy. Also you are right that there are solutions already but if we can use it from a single library then its definitely welcome.

**Comment by slavenf** [comment]
And, yes, segmented vector and devector are ideal for game development. I haven't worked in game industry, but I worked on complex mathematical software that crunched a lot of data and segmented vector was ideal data structure. Segmented vector with billions of elements was nothing unusual for me. 

Have you noticed that I have other project on GitHub, [`pool_allocator`](https://github.com/slavenf/sfl-pool-allocator)? Segmented vector is great, but I wasn't satisfied with segmented vector alone so I got the idea to have `segmented_vector<vector<T>, N, pool_allocator<vector<T>>>` and that would allow me to utilize the last bits of RAM. Memory fragmentation would be minimized with pool allocator. 

My pool allocator is functional but there is room for improvements. I am not working on pool allocator any more, but I have not abandoned that project neither. Maybe you can take a look on that. Maybe we can collaborate on that if you have a need for something like that. I am sure that all huge game development companies have their own allocators, but I haven't found something similar on the Internet.

**Comment by slavenf** [comment]
> 
> If you already have static_vector and static_flat_set I think it would be a good addition, for game development we definitely try to avoid as many allocations as possible, here is an example of one https://github.com/OpenRCT2/OpenRCT2/blob/dec5140f20d57cf3a534ff4ee7685c1f78298aee/src/openrct2/ride/RideConstruction.cpp#L1464 , there are probably way more scenarios where this is useful, I mean people will probably just use a vector for such things but when the maximum is known and its not a large amount of elements then a fixed/static vector is always handy. Also you are right that there are solutions already but if we can use it from a single library then its definitely welcome.

I see. Ok, I will add static_vector and static_flat_set into my library, but I must make few changes to these containers since they are way out of the sync with master branch. I will start working on that when I release new version with segmented devector.

**Comment by ZehMatt** [comment]
I'm aware of the pool_allocator but I didn't have the chance/need to use it yet, I definitely have it on my todo list of things that I want to try out. I can also definitely relate to working with a huge amount of data, in one former jobs it was not uncommon that our machines ended up with 20 to 60 GB memory usage, that was even at a time where having 6 to 8 GB memory were enough for most people 😄

> I see. Ok, I will add static_vector and static_flat_set into my library, but I must make few changes to these containers since they are way out of the sync with master branch. I will start working on that when I release new version with segmented devector.
 
Great, I definitely think its a good addition, there are also very few libraries out there where you wont be pulling in a ton of stuff that you don't need which is what makes this one really fantastic.

**Comment by slavenf** [comment]
@ZehMatt New version is released :-) I will add static_vector to this library very soon. Stay tuned. Later, I will add static flat maps and sets also.

> Great, I definitely think its a good addition, there are also very few libraries out there where you wont be pulling in a ton of stuff that you don't need which is what makes this one really fantastic.

I also do not like such libraries. Boost library has great sub-libraries, but I have been successfully avoiding boost library just because it is huuuuge.

**Comment by ZehMatt** [comment]
Going to close this issue as sfl::segmented_devector is now official, thanks again.
